### ISSUE TITLE
Personal Page throws error if UserId is directly typed into URL

### ISSUE THREAD

**Issue by Y-Negash** [Aebel-Shajan/connect-cards#12]
#10 

The issue was initially when a link is clicked and redirects to the new page, if you go back and click the link again an error shows up about the link being undefined. This issue stopped when I changed it so that the link opened in a new tab.

Now though, if you want to **type** the user's name directly after the URL or if you click e.g. http://localhost:5173/Rayquaza then the following error is displayed:

![image](https://github.com/user-attachments/assets/43bb9b93-a5ee-4df8-aeda-08d2516307d6)

This could be because I moved `users` state from `Home` to `App` since I couldn't get users to be passed down to personal page any other way. The setting of the `users` state could be happening slower than the rendering of Personal Page so users ends up undefined?

**Comment by Aebel-Shajan** [comment]
I asked chatgpt about why the users state does not get populated when we go to http://localhost:5173/aebel manually.

https://chatgpt.com/share/4696ad97-e1b8-466b-9a8d-eba12c67b024

**Comment by Aebel-Shajan** [comment]
I'll push up a pull request for this quick

**Comment by Aebel-Shajan** [comment]
Wait nvm i thought i had it but it no workey. You can have a crack at it if you want, i gotta go to a meeting
