### ISSUE TITLE
The routes are case sensitive 

### ISSUE THREAD

**Issue by Aebel-Shajan** [Aebel-Shajan/connect-cards#16]
Going to https://connect-cards.vercel.app/Aebel works but going to https://connect-cards.vercel.app/aebel does not. We should modify the code such that both links redirect to the same page.

**Comment by Y-Negash** [comment]
User's name is lowercase as default now on the personal page, would look better if uppercase.


![image](https://github.com/user-attachments/assets/7e6d0ad2-f931-48b5-9452-1eb28de4562b)
