### ISSUE TITLE
Fix: Code formatting and refactoring.

### ISSUE THREAD

**Issue by Aebel-Shajan** [Aebel-Shajan/connect-cards#45]
The code has begun to get a bit more messy. I reckon we should make a branch to restructure, reformat and refactor the code. 

Stuff we could do: 
* Move user card component outside of home component. This is cus its also used in the personal page component.
* Add prop types to all components.
* Add JSdoc to all functions?
* Run npm run format and npm run lint.

**Comment by Y-Negash** [comment]
good point, we can do this once pr #42 has been merged and we're done with the styling. Once everything is in main, these can be done on a new branch.
